.PHONY: web framework-gin direct cloud-aws cloud-gcp cloud-azure

web:
	go run web/main.go

framework-gin:
	go run framework/gin/main.go

direct:
	go run direct/main.go

cloud-aws:
	go run cloud/aws/main.go

cloud-gcp:
	go run cloud/gcp/main.go

cloud-azure:
	go run cloud/azure/main.go
