### Index

GET http://localhost:8080/ HTTP/1.1
X-Client-Type: api

### Portal

GET http://localhost:8080/portal HTTP/1.1
X-Client-Type: api

### Create user

POST http://localhost:8080/new_user HTTP/1.1
X-Client-Type: api

{
    "name": "test",
    "email": "test@gmail.com"
}

### Create bucket

POST http://localhost:8080/buckets/new_bucket HTTP/1.1
X-Client-Type: api

{
    "bucket_name": "test_bucket",
    "description": "test bucket",
    "owner_id": "a93ed55b-bcdd-4303-8314-b5231e33fb62"
}

### Upload file

POST http://localhost:8080/files/test_bucket/upload HTTP/1.1
X-Client-Type: api
Content-Type: multipart/form-data; boundary=----MyBoundary

------MyBoundary
Content-Disposition: form-data; name="folder"

image/background
------MyBoundary
Content-Disposition: form-data; name="file"; filename="fukuma.jpg"
Content-Type: image/jpeg

< /Users/user/Downloads/Wallpapers/fukuma.jpg
------MyBoundary--

### Download file

POST http://localhost:8080/files/test_bucket/download HTTP/1.1
X-Client-Type: api

{
    "bucket_name": "test_bucket",
    "folder_path": "image/background",
    "filename": "fukuma.jpg"
}

### Serve file

GET http://localhost:8080/files/test_bucket/serve?filepath=test_bucket/image/background/fukuma.jpg HTTP/1.1
X-Client-Type: api

### Fetch Subfolders

POST http://localhost:8080/folders/test_bucket/fetch/folders HTTP/1.1
X-Client-Type: api

{
    "bucket_name": "test_bucket",
    "folder_path": "image"
}

### Fetch Files in Folder

POST http://localhost:8080/folders/test_bucket/fetch/files HTTP/1.1
X-Client-Type: api

{
    "bucket_name": "test_bucket",
    "folder_path": "image/background"
}