### Serve file

GET http://localhost:8080/serve/00000000-0000-0000-0000-000000000000 HTTP/1.1

### Upload file

POST http://localhost:8080/buckt/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----MyBoundary

------MyBoundary
Content-Disposition: form-data; parent_id="00000000-0000-0000-0000-000000000000"

image/background
------MyBoundary
Content-Disposition: form-data; name="file"; filename="fukuma.jpg"
Content-Type: image/jpeg

< /Users/user/Downloads/Wallpapers/fukuma.jpg
------MyBoundary--

### Download file

GET http://localhost:8080/buckt/download/00000000-0000-0000-0000-000000000000 HTTP/1.1

### Delete file

DELETE http://localhost:8080/buckt/delete/00000000-0000-0000-0000-000000000000 HTTP/1.1

### Create a new folder

POST http://localhost:8080/buckt/new_folder HTTP/1.1
{
    "parent_id": "00000000-0000-0000-0000-000000000000",
    "folder_name": "New Folder",
    "description": "This is a new folder"
}

### Folder Contents

GET http://localhost:8080/buckt/folder_content/00000000-0000-0000-0000-000000000000 HTTP/1.1
